spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: 6379
      host: localhost
    mongodb:
      host: localhost
      username: admin
      password: admin123
      database: event-management
      authentication-database: admin
      port: 27017

  cache:
    type: redis
