spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: 6379
      host: localhost
    mongodb:
      host: localhost
      username: admin
      password: admin123
      database: event-management
      authentication-database: admin
      port: 27017

  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: Q678WETA8G83628R276ED5YJYTYF86R5RFUF6EUU64D5YJDY577I75
  access-token:
      expiration: 500000
  refresh-token:
    expiration: 3600000